# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sat Apr 17 23:26:55 2021
#

import wx
# begin wxGlade: dependencies
import wx.adv
import wx.grid
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

from views.imageRenderer import ImageRenderer


class MainFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((1024, 768))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.notebook_1 = wx.Notebook(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)

        self.nb_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nb_pane_1, u"Összesítés")

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.nb_pane_1, wx.ID_ANY, u"Összesítés", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_2.Add(label_1, 0, wx.ALL | wx.EXPAND, 6)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 0, wx.EXPAND, 0)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_4, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.nb_pane_1, wx.ID_ANY, u"Tantárgy", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_4.Add(label_2, 0, wx.ALL | wx.EXPAND, 6)

        self.subject_summary_combo_box = wx.ComboBox(self.nb_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_4.Add(self.subject_summary_combo_box, 1, wx.ALL | wx.EXPAND, 6)

        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_3.Add(sizer_6, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.nb_pane_1, wx.ID_ANY, "Csoport", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_6.Add(label_4, 0, wx.ALL | wx.EXPAND, 6)

        self.group_summary_combo_box = wx.ComboBox(self.nb_pane_1, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_6.Add(self.group_summary_combo_box, 0, wx.ALL | wx.EXPAND, 6)

        sizer_33 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_33, 0, wx.EXPAND, 0)

        sizer_33.Add((20, 20), 1, 0, 0)

        label_23 = wx.StaticText(self.nb_pane_1, wx.ID_ANY, u"Kijelölt tanuló", style=wx.ALIGN_RIGHT)
        sizer_33.Add(label_23, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.text_ctrl_8 = wx.TextCtrl(self.nb_pane_1, wx.ID_ANY, "")
        sizer_33.Add(self.text_ctrl_8, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        sizer_33.Add((20, 20), 1, 0, 0)

        self.grades_summary_grid = wx.grid.Grid(self.nb_pane_1, wx.ID_ANY, size=(1, 1))
        self.grades_summary_grid.CreateGrid(36, 33)
        self.grades_summary_grid.SetRowLabelSize(30)
        self.grades_summary_grid.SetSelectionMode(wx.grid.Grid.SelectRows)
        self.grades_summary_grid.SetColLabelValue(0, u"Tanuló")
        self.grades_summary_grid.SetColSize(0, 120)
        self.grades_summary_grid.SetColLabelValue(1, "1")
        self.grades_summary_grid.SetColSize(1, 30)
        self.grades_summary_grid.SetColLabelValue(2, "2")
        self.grades_summary_grid.SetColSize(2, 30)
        self.grades_summary_grid.SetColLabelValue(3, "3")
        self.grades_summary_grid.SetColSize(3, 30)
        self.grades_summary_grid.SetColLabelValue(4, "4")
        self.grades_summary_grid.SetColSize(4, 30)
        self.grades_summary_grid.SetColLabelValue(5, "5")
        self.grades_summary_grid.SetColSize(5, 30)
        self.grades_summary_grid.SetColLabelValue(6, "6")
        self.grades_summary_grid.SetColSize(6, 30)
        self.grades_summary_grid.SetColLabelValue(7, "7")
        self.grades_summary_grid.SetColSize(7, 30)
        self.grades_summary_grid.SetColLabelValue(8, "8")
        self.grades_summary_grid.SetColSize(8, 30)
        self.grades_summary_grid.SetColLabelValue(9, "9")
        self.grades_summary_grid.SetColSize(9, 30)
        self.grades_summary_grid.SetColLabelValue(10, "10")
        self.grades_summary_grid.SetColSize(10, 30)
        self.grades_summary_grid.SetColLabelValue(11, u"fél")
        self.grades_summary_grid.SetColSize(11, 30)
        self.grades_summary_grid.SetColLabelValue(12, u"írt")
        self.grades_summary_grid.SetColSize(12, 30)
        self.grades_summary_grid.SetColLabelValue(13, "11")
        self.grades_summary_grid.SetColSize(13, 30)
        self.grades_summary_grid.SetColLabelValue(14, "12")
        self.grades_summary_grid.SetColSize(14, 30)
        self.grades_summary_grid.SetColLabelValue(15, "13")
        self.grades_summary_grid.SetColSize(15, 30)
        self.grades_summary_grid.SetColLabelValue(16, "14")
        self.grades_summary_grid.SetColSize(16, 30)
        self.grades_summary_grid.SetColLabelValue(17, "15")
        self.grades_summary_grid.SetColSize(17, 30)
        self.grades_summary_grid.SetColLabelValue(18, "16")
        self.grades_summary_grid.SetColSize(18, 30)
        self.grades_summary_grid.SetColLabelValue(19, "17")
        self.grades_summary_grid.SetColSize(19, 30)
        self.grades_summary_grid.SetColLabelValue(20, "18")
        self.grades_summary_grid.SetColSize(20, 30)
        self.grades_summary_grid.SetColLabelValue(21, "19")
        self.grades_summary_grid.SetColSize(21, 30)
        self.grades_summary_grid.SetColLabelValue(22, "20")
        self.grades_summary_grid.SetColSize(22, 30)
        self.grades_summary_grid.SetColLabelValue(23, u"év")
        self.grades_summary_grid.SetColSize(23, 30)
        self.grades_summary_grid.SetColLabelValue(24, u"írt")
        self.grades_summary_grid.SetColSize(24, 30)
        self.grades_summary_grid.SetColLabelValue(25, "1")
        self.grades_summary_grid.SetColSize(25, 30)
        self.grades_summary_grid.SetColLabelValue(26, "1")
        self.grades_summary_grid.SetColSize(26, 30)
        self.grades_summary_grid.SetColLabelValue(27, "1")
        self.grades_summary_grid.SetColSize(27, 30)
        self.grades_summary_grid.SetColLabelValue(28, "1")
        self.grades_summary_grid.SetColSize(28, 30)
        self.grades_summary_grid.SetColLabelValue(29, "2")
        self.grades_summary_grid.SetColSize(29, 30)
        self.grades_summary_grid.SetColLabelValue(30, "2")
        self.grades_summary_grid.SetColSize(30, 30)
        self.grades_summary_grid.SetColLabelValue(31, "2")
        self.grades_summary_grid.SetColSize(31, 30)
        self.grades_summary_grid.SetColLabelValue(32, "2")
        self.grades_summary_grid.SetColSize(32, 30)
        sizer_2.Add(self.grades_summary_grid, 1, wx.EXPAND, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_7, 0, wx.EXPAND, 0)

        self.mark_student_button = wx.Button(self.nb_pane_1, wx.ID_ANY, u"Tanuló jelölése")
        sizer_7.Add(self.mark_student_button, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        label_5 = wx.StaticText(self.nb_pane_1, wx.ID_ANY, u"Név")
        sizer_7.Add(label_5, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.text_ctrl_1 = wx.TextCtrl(self.nb_pane_1, wx.ID_ANY, "")
        sizer_7.Add(self.text_ctrl_1, 2, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        label_6 = wx.StaticText(self.nb_pane_1, wx.ID_ANY, u"Egyéni jegy")
        sizer_7.Add(label_6, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.text_ctrl_2 = wx.TextCtrl(self.nb_pane_1, wx.ID_ANY, "")
        sizer_7.Add(self.text_ctrl_2, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.save_individual_grade_button = wx.Button(self.nb_pane_1, wx.ID_ANY, u"Mentés")
        sizer_7.Add(self.save_individual_grade_button, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.nb_pane_2 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nb_pane_2, u"Eredmény")

        sizer_8 = wx.BoxSizer(wx.VERTICAL)

        label_7 = wx.StaticText(self.nb_pane_2, wx.ID_ANY, u"Eredmény", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_8.Add(label_7, 0, wx.ALL | wx.EXPAND, 6)

        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_9, 0, wx.EXPAND, 0)

        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(sizer_10, 1, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.nb_pane_2, wx.ID_ANY, u"Tantárgy", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_10.Add(label_8, 0, wx.ALL | wx.EXPAND, 6)

        self.subject_result_combo_box = wx.ComboBox(self.nb_pane_2, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_10.Add(self.subject_result_combo_box, 0, wx.ALL | wx.EXPAND, 6)

        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(sizer_11, 1, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.nb_pane_2, wx.ID_ANY, "Csoport", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_11.Add(label_9, 0, wx.ALL | wx.EXPAND, 6)

        self.group_result_combo_box = wx.ComboBox(self.nb_pane_2, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_11.Add(self.group_result_combo_box, 0, wx.ALL | wx.EXPAND, 6)

        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_9.Add(sizer_12, 1, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.nb_pane_2, wx.ID_ANY, "Dolgozat", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_12.Add(label_10, 0, wx.ALL | wx.EXPAND, 6)

        self.exam_result_combo_box = wx.ComboBox(self.nb_pane_2, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_12.Add(self.exam_result_combo_box, 0, wx.ALL | wx.EXPAND, 6)

        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_13, 0, wx.EXPAND, 0)

        label_11 = wx.StaticText(self.nb_pane_2, wx.ID_ANY, u"Maximális pontszám")
        sizer_13.Add(label_11, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.text_ctrl_3 = wx.TextCtrl(self.nb_pane_2, wx.ID_ANY, "")
        sizer_13.Add(self.text_ctrl_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        label_12 = wx.StaticText(self.nb_pane_2, wx.ID_ANY, u"Dátum")
        sizer_13.Add(label_12, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.text_ctrl_4 = wx.TextCtrl(self.nb_pane_2, wx.ID_ANY, "")
        sizer_13.Add(self.text_ctrl_4, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(sizer_14, 1, wx.EXPAND, 0)

        self.grades_result_grid = wx.grid.Grid(self.nb_pane_2, wx.ID_ANY, size=(1, 1))
        self.grades_result_grid.CreateGrid(36, 4)
        self.grades_result_grid.SetRowLabelSize(30)
        self.grades_result_grid.SetColLabelSize(50)
        self.grades_result_grid.SetColLabelValue(0, u"Tanuló")
        self.grades_result_grid.SetColSize(0, 150)
        self.grades_result_grid.SetColLabelValue(1, u"Elért\npontszám")
        self.grades_result_grid.SetColSize(1, 75)
        self.grades_result_grid.SetColLabelValue(2, u"Elért\nszázalék")
        self.grades_result_grid.SetColSize(2, 75)
        self.grades_result_grid.SetColLabelValue(3, u"Érdemjegy")
        self.grades_result_grid.SetColSize(3, 100)
        sizer_14.Add(self.grades_result_grid, 2, wx.ALL | wx.EXPAND, 6)

        sizer_15 = wx.BoxSizer(wx.VERTICAL)
        sizer_14.Add(sizer_15, 1, wx.EXPAND, 0)

        sizer_31 = wx.BoxSizer(wx.VERTICAL)
        sizer_15.Add(sizer_31, 1, wx.EXPAND, 0)

        label_21 = wx.StaticText(self.nb_pane_2, wx.ID_ANY, u"Százalék", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_31.Add(label_21, 0, wx.ALL | wx.EXPAND, 6)

        self.percent_point_limits_grid = wx.grid.Grid(self.nb_pane_2, wx.ID_ANY, size=(1, 1))
        self.percent_point_limits_grid.CreateGrid(6, 3)
        self.percent_point_limits_grid.SetRowLabelSize(1)
        self.percent_point_limits_grid.SetColLabelSize(1)
        self.percent_point_limits_grid.EnableDragRowSize(0)
        self.percent_point_limits_grid.EnableDragGridSize(0)
        self.percent_point_limits_grid.SetColLabelValue(0, "")
        self.percent_point_limits_grid.SetColSize(0, 50)
        self.percent_point_limits_grid.SetColLabelValue(1, "")
        self.percent_point_limits_grid.SetColSize(1, 50)
        self.percent_point_limits_grid.SetColLabelValue(2, "")
        self.percent_point_limits_grid.SetColSize(2, 100)
        sizer_31.Add(self.percent_point_limits_grid, 1, wx.ALL | wx.EXPAND, 6)

        sizer_32 = wx.BoxSizer(wx.VERTICAL)
        sizer_15.Add(sizer_32, 1, wx.EXPAND, 0)

        label_22 = wx.StaticText(self.nb_pane_2, wx.ID_ANY, u"Pontszám", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_32.Add(label_22, 0, wx.ALL | wx.EXPAND, 6)

        self.num_point_limits_grid = wx.grid.Grid(self.nb_pane_2, wx.ID_ANY, size=(1, 1))
        self.num_point_limits_grid.CreateGrid(5, 4)
        self.num_point_limits_grid.SetRowLabelSize(1)
        self.num_point_limits_grid.SetColLabelSize(1)
        self.num_point_limits_grid.EnableDragRowSize(0)
        self.num_point_limits_grid.EnableDragGridSize(0)
        self.num_point_limits_grid.SetColSize(0, 50)
        self.num_point_limits_grid.SetColSize(1, 50)
        self.num_point_limits_grid.SetColSize(2, 100)
        self.num_point_limits_grid.SetColSize(3, 30)
        sizer_32.Add(self.num_point_limits_grid, 1, wx.ALL | wx.EXPAND, 6)

        self.border_result_button = wx.Button(self.nb_pane_2, wx.ID_ANY, u"Mentés")
        sizer_15.Add(self.border_result_button, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 6)

        self.nb_pane_3 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nb_pane_3, u"Pontozás")

        sizer_16 = wx.BoxSizer(wx.VERTICAL)

        label_13 = wx.StaticText(self.nb_pane_3, wx.ID_ANY, u"Pontozás", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_16.Add(label_13, 0, wx.ALL | wx.EXPAND, 6)

        sizer_17 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16.Add(sizer_17, 0, wx.EXPAND, 0)

        sizer_18 = wx.BoxSizer(wx.VERTICAL)
        sizer_17.Add(sizer_18, 1, wx.EXPAND, 0)

        label_14 = wx.StaticText(self.nb_pane_3, wx.ID_ANY, u"Tantárgy", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_18.Add(label_14, 0, wx.ALL | wx.EXPAND, 6)

        self.subject_score_combo_box = wx.ComboBox(self.nb_pane_3, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_18.Add(self.subject_score_combo_box, 0, wx.ALL | wx.EXPAND, 6)

        sizer_19 = wx.BoxSizer(wx.VERTICAL)
        sizer_17.Add(sizer_19, 1, wx.EXPAND, 0)

        label_15 = wx.StaticText(self.nb_pane_3, wx.ID_ANY, "Csoport", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_19.Add(label_15, 0, wx.ALL | wx.EXPAND, 6)

        self.group_score_combo_box = wx.ComboBox(self.nb_pane_3, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_19.Add(self.group_score_combo_box, 0, wx.ALL | wx.EXPAND, 6)

        sizer_20 = wx.BoxSizer(wx.VERTICAL)
        sizer_17.Add(sizer_20, 1, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.nb_pane_3, wx.ID_ANY, "Dolgozat", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_20.Add(label_16, 0, wx.ALL | wx.EXPAND, 6)

        self.combo_box_9 = wx.ComboBox(self.nb_pane_3, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_20.Add(self.combo_box_9, 1, wx.ALL | wx.EXPAND, 6)

        sizer_22 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16.Add(sizer_22, 0, wx.EXPAND, 0)

        self.new_exam_button = wx.Button(self.nb_pane_3, wx.ID_ANY, u"Új dolgozat")
        sizer_22.Add(self.new_exam_button, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.save_exam_score_button = wx.Button(self.nb_pane_3, wx.ID_ANY, u"Mentés")
        sizer_22.Add(self.save_exam_score_button, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.checkbox_1 = wx.CheckBox(self.nb_pane_3, wx.ID_ANY, u"Látható jegyek")
        sizer_22.Add(self.checkbox_1, 0, wx.EXPAND, 0)

        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_16.Add(sizer_23, 0, wx.EXPAND, 0)

        label_17 = wx.StaticText(self.nb_pane_3, wx.ID_ANY, u"Dolgozat témája")
        sizer_23.Add(label_17, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.exam_subjetct_text_ctrl = wx.TextCtrl(self.nb_pane_3, wx.ID_ANY, "")
        sizer_23.Add(self.exam_subjetct_text_ctrl, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        label_18 = wx.StaticText(self.nb_pane_3, wx.ID_ANY, u"Dátum")
        sizer_23.Add(label_18, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.exam_date_datepicker_ctrl = wx.adv.DatePickerCtrl(self.nb_pane_3, wx.ID_ANY)
        sizer_23.Add(self.exam_date_datepicker_ctrl, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 6)

        self.score_grid = wx.grid.Grid(self.nb_pane_3, wx.ID_ANY, size=(1, 1))
        self.score_grid.CreateGrid(38, 24)
        self.score_grid.SetRowLabelSize(30)
        self.score_grid.SetColLabelValue(0, u"Név")
        self.score_grid.SetColSize(0, 140)
        self.score_grid.SetColLabelValue(1, "1")
        self.score_grid.SetColSize(1, 30)
        self.score_grid.SetColLabelValue(2, "2")
        self.score_grid.SetColSize(2, 30)
        self.score_grid.SetColLabelValue(3, "3")
        self.score_grid.SetColSize(3, 30)
        self.score_grid.SetColLabelValue(4, "4")
        self.score_grid.SetColSize(4, 30)
        self.score_grid.SetColLabelValue(5, "5")
        self.score_grid.SetColSize(5, 30)
        self.score_grid.SetColLabelValue(6, "6")
        self.score_grid.SetColSize(6, 30)
        self.score_grid.SetColLabelValue(7, "7")
        self.score_grid.SetColSize(7, 30)
        self.score_grid.SetColLabelValue(8, "8")
        self.score_grid.SetColSize(8, 30)
        self.score_grid.SetColLabelValue(9, "9")
        self.score_grid.SetColSize(9, 30)
        self.score_grid.SetColLabelValue(10, "10")
        self.score_grid.SetColSize(10, 30)
        self.score_grid.SetColLabelValue(11, "11")
        self.score_grid.SetColSize(11, 30)
        self.score_grid.SetColLabelValue(12, "12")
        self.score_grid.SetColSize(12, 30)
        self.score_grid.SetColLabelValue(13, "13")
        self.score_grid.SetColSize(13, 30)
        self.score_grid.SetColLabelValue(14, "14")
        self.score_grid.SetColSize(14, 30)
        self.score_grid.SetColLabelValue(15, "15")
        self.score_grid.SetColSize(15, 30)
        self.score_grid.SetColLabelValue(16, "16")
        self.score_grid.SetColSize(16, 30)
        self.score_grid.SetColLabelValue(17, "17")
        self.score_grid.SetColSize(17, 30)
        self.score_grid.SetColLabelValue(18, "18")
        self.score_grid.SetColSize(18, 30)
        self.score_grid.SetColLabelValue(19, "19")
        self.score_grid.SetColSize(19, 30)
        self.score_grid.SetColLabelValue(20, "20")
        self.score_grid.SetColSize(20, 30)
        self.score_grid.SetColLabelValue(21, u"Össz")
        self.score_grid.SetColSize(21, 40)
        self.score_grid.SetColLabelValue(22, "Jegy")
        self.score_grid.SetColSize(22, 40)
        self.score_grid.SetColLabelValue(23, u"Megjegyzés")
        self.score_grid.SetColSize(23, 200)
        self.score_grid.SetRowLabelValue(0, "El.")
        self.score_grid.SetRowLabelValue(1, "Le.")
        self.score_grid.SetRowSize(1, 100)
        self.score_grid.SetRowLabelValue(2, "1")
        self.score_grid.SetRowLabelValue(3, "2")
        self.score_grid.SetRowLabelValue(4, "3")
        self.score_grid.SetRowLabelValue(5, "4")
        self.score_grid.SetRowLabelValue(6, "5")
        self.score_grid.SetRowLabelValue(7, "6")
        self.score_grid.SetRowLabelValue(8, "7")
        self.score_grid.SetRowLabelValue(9, "8")
        self.score_grid.SetRowLabelValue(10, "9")
        self.score_grid.SetRowLabelValue(11, "10")
        self.score_grid.SetRowLabelValue(12, "11")
        self.score_grid.SetRowLabelValue(13, "12")
        self.score_grid.SetRowLabelValue(14, "13")
        self.score_grid.SetRowLabelValue(15, "14")
        self.score_grid.SetRowLabelValue(16, "15")
        self.score_grid.SetRowLabelValue(17, "16")
        self.score_grid.SetRowLabelValue(18, "17")
        self.score_grid.SetRowLabelValue(19, "18")
        self.score_grid.SetRowLabelValue(20, "19")
        self.score_grid.SetRowLabelValue(21, "20")
        self.score_grid.SetRowLabelValue(22, "21")
        self.score_grid.SetRowLabelValue(23, "22")
        self.score_grid.SetRowLabelValue(24, "23")
        self.score_grid.SetRowLabelValue(25, "24")
        self.score_grid.SetRowLabelValue(26, "25")
        self.score_grid.SetRowLabelValue(27, "26")
        self.score_grid.SetRowLabelValue(28, "27")
        self.score_grid.SetRowLabelValue(29, "28")
        self.score_grid.SetRowLabelValue(30, "29")
        self.score_grid.SetRowLabelValue(31, "30")
        self.score_grid.SetRowLabelValue(32, "31")
        self.score_grid.SetRowLabelValue(33, "32")
        self.score_grid.SetRowLabelValue(34, "33")
        self.score_grid.SetRowLabelValue(35, "34")
        self.score_grid.SetRowLabelValue(36, "35")
        self.score_grid.SetRowLabelValue(37, "36")
        sizer_16.Add(self.score_grid, 2, wx.EXPAND, 0)

        self.nb_pane_4 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nb_pane_4, u"Tanulók")

        sizer_24 = wx.BoxSizer(wx.VERTICAL)

        label_19 = wx.StaticText(self.nb_pane_4, wx.ID_ANY, u"Tanulókezelés", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_24.Add(label_19, 0, wx.ALL | wx.EXPAND, 6)

        sizer_25 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_24.Add(sizer_25, 0, wx.EXPAND, 0)

        sizer_25.Add((20, 20), 1, 0, 0)

        self.group_combo_box = wx.ComboBox(self.nb_pane_4, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        sizer_25.Add(self.group_combo_box, 1, 0, 0)

        sizer_25.Add((20, 20), 1, 0, 0)

        sizer_26 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_24.Add(sizer_26, 1, wx.EXPAND, 0)

        self.student_list_box = wx.ListBox(self.nb_pane_4, wx.ID_ANY, choices=[])
        sizer_26.Add(self.student_list_box, 1, wx.ALL | wx.EXPAND, 6)

        self.save_student_button = wx.Button(self.nb_pane_4, wx.ID_ANY, u"Mentés")
        sizer_26.Add(self.save_student_button, 0, wx.ALL, 6)

        self.student_edit_text_ctrl = wx.TextCtrl(self.nb_pane_4, wx.ID_ANY, "")
        sizer_24.Add(self.student_edit_text_ctrl, 0, wx.ALL | wx.EXPAND, 6)

        sizer_27 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_24.Add(sizer_27, 0, wx.EXPAND, 0)

        self.add_student_button = wx.Button(self.nb_pane_4, wx.ID_ANY, u"Hozzáad")
        sizer_27.Add(self.add_student_button, 0, wx.ALL, 6)

        self.edit_student_button = wx.Button(self.nb_pane_4, wx.ID_ANY, u"Szerkesztés")
        sizer_27.Add(self.edit_student_button, 0, wx.ALL, 6)

        self.modify_student_button = wx.Button(self.nb_pane_4, wx.ID_ANY, u"Módosítás")
        sizer_27.Add(self.modify_student_button, 0, wx.ALL, 6)

        self.delete_student_button = wx.Button(self.nb_pane_4, wx.ID_ANY, u"Törlés")
        sizer_27.Add(self.delete_student_button, 0, wx.ALL, 6)

        self.nbpane_5 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.notebook_1.AddPage(self.nbpane_5, "Csoportok")

        sizer_28 = wx.BoxSizer(wx.VERTICAL)

        label_20 = wx.StaticText(self.nbpane_5, wx.ID_ANY, u"Csoportkezelés", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_28.Add(label_20, 0, wx.ALL | wx.EXPAND, 6)

        sizer_29 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_28.Add(sizer_29, 1, wx.EXPAND, 0)

        self.group_list_box = wx.ListBox(self.nbpane_5, wx.ID_ANY, choices=[])
        sizer_29.Add(self.group_list_box, 1, wx.ALL | wx.EXPAND, 6)

        self.save_group_button = wx.Button(self.nbpane_5, wx.ID_ANY, u"Mentés")
        sizer_29.Add(self.save_group_button, 0, wx.ALL, 6)

        self.text_ctrl_7 = wx.TextCtrl(self.nbpane_5, wx.ID_ANY, "")
        sizer_28.Add(self.text_ctrl_7, 0, wx.ALL | wx.EXPAND, 6)

        sizer_30 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_28.Add(sizer_30, 1, wx.EXPAND, 0)

        self.add_group_button = wx.Button(self.nbpane_5, wx.ID_ANY, u"Hozzáadás")
        sizer_30.Add(self.add_group_button, 0, wx.ALL, 6)

        self.edit_group_button = wx.Button(self.nbpane_5, wx.ID_ANY, u"Szerkesztés")
        sizer_30.Add(self.edit_group_button, 0, wx.ALL, 6)

        self.modify_group_button = wx.Button(self.nbpane_5, wx.ID_ANY, u"Módosítás")
        sizer_30.Add(self.modify_group_button, 0, wx.ALL, 6)

        self.delete_group_button = wx.Button(self.nbpane_5, wx.ID_ANY, u"Törlés")
        sizer_30.Add(self.delete_group_button, 0, wx.ALL, 6)

        self.nbpane_5.SetSizer(sizer_28)

        self.nb_pane_4.SetSizer(sizer_24)

        self.nb_pane_3.SetSizer(sizer_16)

        self.nb_pane_2.SetSizer(sizer_8)

        self.nb_pane_1.SetSizer(sizer_2)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade
        
        imageRenderer = ImageRenderer('Témaűő')
        self.score_grid.SetCellRenderer(1,2,imageRenderer)

# end of class MainFrame
