/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author resahh
 */
public class RMainForm extends javax.swing.JFrame {

    /**
     * Creates new form RMainForm
     */
    public RMainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        groupTbp = new javax.swing.JPanel();
        groupNorthPnl = new javax.swing.JPanel();
        groupEastPnl = new javax.swing.JPanel();
        groupSouthPnl = new javax.swing.JPanel();
        groupWestPnl = new javax.swing.JPanel();
        groupCenterPnl = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        groupAddBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        groupEditBtn = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        groupModifyBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        groupDeleteBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        groupTf = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        groupTbl = new javax.swing.JTable();
        studentTbp = new javax.swing.JPanel();
        examTbp = new javax.swing.JPanel();
        scorerTbp = new javax.swing.JPanel();
        resultTbp = new javax.swing.JPanel();
        summaTbp = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        groupTbp.setLayout(new java.awt.BorderLayout());

        groupNorthPnl.setPreferredSize(new java.awt.Dimension(517, 20));

        javax.swing.GroupLayout groupNorthPnlLayout = new javax.swing.GroupLayout(groupNorthPnl);
        groupNorthPnl.setLayout(groupNorthPnlLayout);
        groupNorthPnlLayout.setHorizontalGroup(
            groupNorthPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        groupNorthPnlLayout.setVerticalGroup(
            groupNorthPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        groupTbp.add(groupNorthPnl, java.awt.BorderLayout.NORTH);

        groupEastPnl.setPreferredSize(new java.awt.Dimension(20, 477));

        javax.swing.GroupLayout groupEastPnlLayout = new javax.swing.GroupLayout(groupEastPnl);
        groupEastPnl.setLayout(groupEastPnlLayout);
        groupEastPnlLayout.setHorizontalGroup(
            groupEastPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        groupEastPnlLayout.setVerticalGroup(
            groupEastPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        groupTbp.add(groupEastPnl, java.awt.BorderLayout.EAST);

        groupSouthPnl.setPreferredSize(new java.awt.Dimension(517, 40));

        javax.swing.GroupLayout groupSouthPnlLayout = new javax.swing.GroupLayout(groupSouthPnl);
        groupSouthPnl.setLayout(groupSouthPnlLayout);
        groupSouthPnlLayout.setHorizontalGroup(
            groupSouthPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        groupSouthPnlLayout.setVerticalGroup(
            groupSouthPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        groupTbp.add(groupSouthPnl, java.awt.BorderLayout.SOUTH);

        groupWestPnl.setPreferredSize(new java.awt.Dimension(20, 437));

        javax.swing.GroupLayout groupWestPnlLayout = new javax.swing.GroupLayout(groupWestPnl);
        groupWestPnl.setLayout(groupWestPnlLayout);
        groupWestPnlLayout.setHorizontalGroup(
            groupWestPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        groupWestPnlLayout.setVerticalGroup(
            groupWestPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        groupTbp.add(groupWestPnl, java.awt.BorderLayout.WEST);

        groupCenterPnl.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(477, 40));

        jLabel1.setFont(new java.awt.Font("Caladea", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Csoport kezelés");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel8.add(jLabel1);

        groupCenterPnl.add(jPanel8, java.awt.BorderLayout.NORTH);

        jPanel7.setPreferredSize(new java.awt.Dimension(477, 250));
        jPanel7.setLayout(new java.awt.GridLayout(4, 1));

        groupAddBtn.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        groupAddBtn.setText("Hozzáadás");
        groupAddBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel6.add(groupAddBtn);

        jPanel7.add(jPanel6);

        groupEditBtn.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        groupEditBtn.setText("Szerkesztés");
        groupEditBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel10.add(groupEditBtn);

        jPanel7.add(jPanel10);

        groupModifyBtn.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        groupModifyBtn.setText("Módosítás");
        groupModifyBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel11.add(groupModifyBtn);

        jPanel7.add(jPanel11);

        groupDeleteBtn.setBackground(new java.awt.Color(255, 0, 102));
        groupDeleteBtn.setFont(new java.awt.Font("Caladea", 1, 14)); // NOI18N
        groupDeleteBtn.setText("Törlés");
        groupDeleteBtn.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel12.add(groupDeleteBtn);

        jPanel7.add(jPanel12);

        groupCenterPnl.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(484, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 484, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel2, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(484, 40));

        groupTf.setText("jTextField1");
        groupTf.setPreferredSize(new java.awt.Dimension(265, 30));
        jPanel4.add(groupTf);

        jPanel9.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jPanel5.setLayout(new java.awt.GridLayout(1, 1));

        groupTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(groupTbl);

        jPanel5.add(jScrollPane1);

        jPanel9.add(jPanel5, java.awt.BorderLayout.CENTER);

        groupCenterPnl.add(jPanel9, java.awt.BorderLayout.CENTER);

        groupTbp.add(groupCenterPnl, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Csoportok", groupTbp);

        javax.swing.GroupLayout studentTbpLayout = new javax.swing.GroupLayout(studentTbp);
        studentTbp.setLayout(studentTbpLayout);
        studentTbpLayout.setHorizontalGroup(
            studentTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        studentTbpLayout.setVerticalGroup(
            studentTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Diákok", studentTbp);

        javax.swing.GroupLayout examTbpLayout = new javax.swing.GroupLayout(examTbp);
        examTbp.setLayout(examTbpLayout);
        examTbpLayout.setHorizontalGroup(
            examTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        examTbpLayout.setVerticalGroup(
            examTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Dolgozatok", examTbp);

        javax.swing.GroupLayout scorerTbpLayout = new javax.swing.GroupLayout(scorerTbp);
        scorerTbp.setLayout(scorerTbpLayout);
        scorerTbpLayout.setHorizontalGroup(
            scorerTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        scorerTbpLayout.setVerticalGroup(
            scorerTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Pontozó", scorerTbp);

        javax.swing.GroupLayout resultTbpLayout = new javax.swing.GroupLayout(resultTbp);
        resultTbp.setLayout(resultTbpLayout);
        resultTbpLayout.setHorizontalGroup(
            resultTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        resultTbpLayout.setVerticalGroup(
            resultTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Eredmény", resultTbp);

        javax.swing.GroupLayout summaTbpLayout = new javax.swing.GroupLayout(summaTbp);
        summaTbp.setLayout(summaTbpLayout);
        summaTbpLayout.setHorizontalGroup(
            summaTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        summaTbpLayout.setVerticalGroup(
            summaTbpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Összesítés", summaTbp);

        getContentPane().add(jTabbedPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel examTbp;
    private javax.swing.JButton groupAddBtn;
    private javax.swing.JPanel groupCenterPnl;
    private javax.swing.JButton groupDeleteBtn;
    private javax.swing.JPanel groupEastPnl;
    private javax.swing.JButton groupEditBtn;
    private javax.swing.JButton groupModifyBtn;
    private javax.swing.JPanel groupNorthPnl;
    private javax.swing.JPanel groupSouthPnl;
    private javax.swing.JTable groupTbl;
    private javax.swing.JPanel groupTbp;
    private javax.swing.JTextField groupTf;
    private javax.swing.JPanel groupWestPnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel resultTbp;
    private javax.swing.JPanel scorerTbp;
    private javax.swing.JPanel studentTbp;
    private javax.swing.JPanel summaTbp;
    // End of variables declaration//GEN-END:variables
}
